/* Generated by MyraPad at 21/02/2021 10:05:30 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System.Drawing;
using System.Numerics;


namespace GBemu
{
	partial class EmUI: Grid
	{
		private void BuildUI()
		{
			BarLeft = new Panel();
			BarLeft.Background = new SolidBrush("#213043FF");
			BarLeft.Id = "BarLeft";

			BarRight = new Panel();
			BarRight.GridColumn = 1;
			BarRight.Background = new SolidBrush("#213043FF");
			BarRight.Id = "BarRight";

			var label1 = new Label();
			label1.Text = "Pokemon Blue";
			label1.Padding = new Thickness(35, 35, 0, 35);

			var PlayButton = new TextButton();
			PlayButton.Text = "Play";
			PlayButton.Margin = new Thickness(0, 23, 0, 0);
			PlayButton.Padding = new Thickness(40, 15, 40, 10);
			PlayButton.GridColumn = 1;
			PlayButton.Background = new SolidBrush("#743897FF");
            PlayButton.TouchDown += PlayRom;
			var grid1 = new Grid();
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			//grid1.Widgets.Add(label1);
			grid1.Widgets.Add(PlayButton);

			var panel1 = new Panel();
			panel1.Background = new SolidBrush("#162539");
			panel1.Widgets.Add(grid1);

			var label2 = new Label();
			label2.Text = "Your Library";

			var panel2 = new Panel();
			panel2.Margin = new Thickness(60);
			panel2.Background = new SolidBrush("#1D2F47FF");
			panel2.Widgets.Add(label2);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(panel1);
			verticalStackPanel1.Widgets.Add(panel2);

			 MainArea = new Panel();
			 MainArea.GridColumn = 1;
			 MainArea.GridRow = 1;
			 MainArea.Background = new SolidBrush("#1D2F47");
			 MainArea.Id = " MainArea";
			 MainArea.Widgets.Add(verticalStackPanel1);

			var textButton2 = new TextButton();
			textButton2.Text = "Play";
			textButton2.MinWidth = 500;
			textButton2.Padding = new Thickness(0, 29);
			textButton2.Background = new SolidBrush("#232B38FF");

			var textButton3 = new TextButton();
			textButton3.Text = "Joy Pad";
			textButton3.MinWidth = 500;
			textButton3.Padding = new Thickness(0, 29);
			textButton3.Background = new SolidBrush("#232B38FF");

			var textButton4 = new TextButton();
			textButton4.Text = "System";
			textButton4.MinWidth = 500;
			textButton4.Padding = new Thickness(0, 29);
			textButton4.Background = new SolidBrush("#232B38FF");

			var textButton5 = new TextButton();
			textButton5.Text = "About";
			textButton5.MinWidth = 500;
			textButton5.Padding = new Thickness(0, 29);
			textButton5.Background = new SolidBrush("#232B38FF");

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Widgets.Add(textButton2);
			verticalStackPanel2.Widgets.Add(textButton3);
			verticalStackPanel2.Widgets.Add(textButton4);
			verticalStackPanel2.Widgets.Add(textButton5);

			MenuBar = new Panel();
			MenuBar.GridRow = 1;
			MenuBar.Background = new SolidBrush("#08111F");
			MenuBar.Id = "MenuBar";
			MenuBar.Widgets.Add(verticalStackPanel2);

			
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 3,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 16,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 19,
			});
			Widgets.Add(BarLeft);
			Widgets.Add(BarRight);
			Widgets.Add( MainArea);
			Widgets.Add(MenuBar);
		}

        private void PlayRom(object sender, System.EventArgs e)
        {
			this.Play = true;
        }

        public Panel BarLeft;
		public Panel BarRight;
		public Panel  MainArea;
		public Panel MenuBar;
	}
}
